branch-defaults:
  master:
    environment: matrix-master-dev
environment-defaults:
  matrix-master-dev:
    branch: master
    repository: null
deploy:
  artifact: build.zip
global:
  application_name: matrix-master
  default_ec2_keyname: torchbearer
  default_platform: 64bit Amazon Linux 2017.03 v2.6.0 running Docker 1.12.6
  default_region: us-west-2
  profile: torchbearer
  sc: git
